In [1]:
import pandas as pd 
from sklearn.model_selection import train_test_split
MCQ=pd.read_csv('data_cleaned.csv')
MCQ.head()

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,Q12,Q13,Q14,Q15,O_Cor,I_Cor,P_Co,T_Cor,Top_Cat,Low_Cat
0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,...,1.0,1.0,1.0,1.0,5.0,4.0,3.0,12.0,1.0,2.0
1,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,1.0,0.0,0.0,5.0,2.0,4.0,11.0,1.0,3.0
2,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,1.0,1.0,1.0,1.0,5.0,2.0,4.0,11.0,1.0,3.0
3,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,3.0,1.0,4.0,8.0,2.0,3.0
4,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,...,1.0,0.0,0.0,0.0,3.0,1.0,2.0,6.0,1.0,3.0

In [5]:
# Separate features (X) and labels (y)
features = MCQ.drop(['O_Cor', 'I_Cor', 'P_Co', 'Top_Cat', 'Low_Cat'], axis=1)
labels = MCQ[['O_Cor', 'I_Cor', 'P_Co','Top_Cat', 'Low_Cat']]

In [6]:
#spliting the data into 60% train and 40% test 
x_train,x_test,y_train,y_test=train_test_split(features,labels,test_size=0.4,random_state=42)

In [7]:
#spliting 40% test into 50% validation and 50% test
x_val,x_test,y_val,y_test=train_test_split(x_test,y_test,test_size=0.5,random_state=42)

In [10]:
#checking if the data is split correctly
for dataset in [y_train,y_val,y_test]:
    print(round(len(dataset)/len(labels),2))

0.6
0.2
0.2

In [11]:
#writing all the data into csv files seperately

x_train.to_csv('train_features.csv',index=False)
x_val.to_csv('val_features.csv',index=False)
x_test.to_csv('test_features.csv',index=False)



y_train.to_csv('train_labels.csv',index=False)
y_val.to_csv('val_labels.csv',index=False)
y_test.to_csv('test_labels.csv',index=False)